### PR TITLE
Preserve old policies and policy ordering

### PR DESCRIPTION
**Pull request by cdrappi**
It looks like Yang moved or removed some policies. This pull request addresses that in a way we might not like, because it makes this repo stateful. Anyway, here's why I'm proposing this change

If you run the current master, you would get:

```sh
$ npm run build-json                                                                                                                                        [2:57:10]

> yang-policies@0.1.0 build-json /Users/christiandrappi/workspace/yang-policies
> node build-json.js

✔ Found Andrew Yang's 114 Policies
✔ Loaded 114 Pages
✔ 114 Andrew Yang's Policies Saved in /policies.json
Commit the latest policies.json file, and publish on npm
```

Beautiful console logging. The colors 😍 ... but also failing tests

If you run this, you will get:
```sh
> yang-policies@0.1.0 build-json /Users/christiandrappi/workspace/yang-policies
> node build-json.js

⠋ Fetching Policies
✔ Found Andrew Yang's 114 Policies
✔ Loaded 114 Pages
✔ 142 Andrew Yang's Policies Saved in /policies.json
Commit the latest policies.json file, and publish on npm
```

And passing tests!

### CODE REVIEW

**Comment by brh55** [comment]
I like this! But we may need some attribute to indicate if a policy is no longer listed on the yang2020 page -- if that ever happens. For now I shall approve! :)

**Comment by cdrappi** [comment]
@brh55 that's a great idea!

**Comment by cdrappi** [comment]
btw you are a total king for making this. thank you

**Comment by brh55** [comment]
@cdrappi Just a quick couple hours of being bored.. 😅  but honestly you are a boss for reading the code, and making it even better! 🥇 Thank you!

**Pull request merged**
